# Generated by Django 4.0 on 2022-01-05 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_name', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('artist', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('genre', models.CharField(choices=[('1', 'Romantic'), ('2', 'Motivational'), ('3', 'Heart broken'), ('4', 'Rock')], default='4', max_length=2)),
                ('language', models.CharField(choices=[('1', 'Tamil'), ('2', 'English'), ('3', 'Hindi'), ('4', 'Malayalam'), ('5', 'Telugu'), ('6', 'Kanada')], max_length=2)),
                ('lyrics', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorite', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('liked', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
