# Generated by Django 4.0 on 2022-01-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_rename_music_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Romantic', 'Romantic'), ('Motivational', 'Motivational'), ('Heart broken', 'Heart broken'), ('Rock', 'Rock')], default='4', max_length=15),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Telugu', 'Telugu'), ('Kanada', 'Kanada')], max_length=10),
        ),
    ]
