# Generated by Django 4.0 on 2022-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Romantic', 'Romantic'), ('Motivational', 'Motivational'), ('Heart broken', 'Heart broken'), ('Rock', 'Rock')], default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Tamil', 'Tamil'), ('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Telugu', 'Telugu'), ('Kanada', 'Kanada')], default='Unknown', max_length=10),
        ),
    ]
