# Generated by Django 4.0 on 2022-01-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_song_genre_alter_song_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='covers'),
        ),
    ]
