# Generated by Django 4.0 on 2022-01-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_remove_song_favorite_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='default.mp3', upload_to='musics/'),
        ),
    ]
