# Generated by Django 4.0 on 2022-01-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='Currently Unavailable', null=True),
        ),
    ]
