# Generated by Django 4.0 on 2022-01-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_song_add_in_pl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='default.jpeg', upload_to='covers/'),
        ),
    ]
