# Generated by Django 4.0 on 2022-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_alter_song_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, default='default.mp3', null=True, upload_to='musics/'),
        ),
    ]
