# Generated by Django 4.0 on 2022-01-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0005_remove_song_favorite_song_cover'),
        ('profiles', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_name', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('artist', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('genre', models.CharField(choices=[('Unknown', 'Unknown'), ('Romantic', 'Romantic'), ('Motivational', 'Motivational'), ('Heart broken', 'Heart broken'), ('Rock', 'Rock')], default='Unknown', max_length=15, null=True)),
                ('language', models.CharField(choices=[('Unknown', 'Unknown'), ('Tamil', 'Tamil'), ('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Telugu', 'Telugu'), ('Kanada', 'Kanada')], default='Unknown', max_length=10, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('album_cover', models.ImageField(default='default.png', upload_to='album_covers')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('parts', models.ManyToManyField(blank=True, to='song.Song')),
            ],
        ),
    ]
