# Generated by Django 4.0 on 2022-01-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_remove_song_favorite_song_cover'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='parts',
            field=models.ManyToManyField(to='song.Song'),
        ),
    ]
