# Generated by Django 4.0 on 2022-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_playlist_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='album_cover',
            field=models.ImageField(default='playDefault.jpeg', upload_to='album_covers/'),
        ),
    ]
